# Generated by Django 4.0.2 on 2022-02-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
